3-module
js-tasks-ru/jsbasic-20230302_gergil-v pull request #4
Opened 2023-03-22 14:15 UTC by gergVlad

2023-03-22 14:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-23 11:03 UTC, SinimaWath requested changes

2023-03-23 11:03 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
Давай замени на вызов 3 функций:
```
filter().map().join('\n')
```

join может принимать аргумент

2023-03-23 13:48 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-25 14:10 UTC, SinimaWath approved these changes

2023-03-25 14:11 UTC, merged